# Generated by Django 3.0.5 on 2020-04-30 11:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200428_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='take',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter a date between now and 4 weeks'),
            preserve_default=False,
        ),
    ]
