# Generated by Django 3.0.5 on 2020-04-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_take'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='take',
        ),
    ]
